In [1]:
import sys
sys.path.append('../../build')
import libry as ry

import numpy as np

In [2]:
C = ry.Config()
C.addFile("../../scenarios/pandasTable.g")

D = C.view()
#C.addFile('../../scenarios/kitchen.g')

In [3]:
C.addObject(name='object', shape=ry.ST.ssBox, pos=[.5, -.5, 1], size=[.1, .1, .25, .02], color=[1., 0., 0.])


In [ ]:
#C.getFrameNames()

In [4]:
coll = C.feature(ry.FS.accumulatedCollisions, [])

C.computeCollisions() 
coll.eval(C)

(array([0.06029473]),
 array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  1.22737475e-02,
         -7.35215471e-08, -1.26279538e-07,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00]]))

In [5]:
dist = C.feature(ry.FS.distance, ['R_gripper', 'object'])
dist.eval(C)

(array([-0.46340618]),
 array([[-0.        , -0.        , -0.        , -0.        , -0.        ,
         -0.        , -0.        , -0.        , -0.02396042, -0.09625804,
         -0.07320569, -0.21504519, -0.03898705, -0.14515982, -0.04508871,
         -0.        ]]))

In [6]:
C.getCollisions(0)

[('R_frame', 'object', -0.0010051162779074994),
 ('R_frame', 'object', -0.03000027850427236),
 ('R_frame', 'object', -0.029289332384357682)]